travis:
  secure:
    BINSTAR_TOKEN: Ofqw0sM3ra1JlDKej9rOH3LjKECC6n9GgkfYa/qiRTl8RkHm8vEczF+YT7XEcmWieespHsQcSipR/5/nj4XOon6B6iQD93Sk70dx9kyyFm8v2aFgcKI3m9Sqa+IOpCdKNn06IYGM7i6U0hUj8HUx0RgECEUfA36pONI3jpxkROv8uNG7Q2C8NZEPidWHNB7NTsH3CO6szWFkmO9kBFYdphV8ehTf7nDiI65KT1okDUbrUReJD6+uRLWhMpe/OhlYic5IQCrJ5eZyEd77bCTWIXsmIbxOhYBaoYu9qY/dlaDtc+f41aLO4PnReEQHTEVWryMHwES8LrA/iuLHLj75g2vdzpETKTHEGS8CwdZbZusGlhcpVODGVH0YAxoJdyRulA6587KmXMdP6T0gz/s9OmUxdvX98qdxN5hV1vzByiHwtVZPJ+ukxoSySwn9tOB144OojIJ5YJlnSYbQ/leMgH3kXF5nEQbtiivYV5tBAQB3qnCOyQMwt9zBtcmg5ZV6pXyqLckJtd81PF8rn6zpLsyAq3srLXf8rsHIh8uHUBx2GXeIvxKGk32lZTOq3J4NrTajIG/i7+tl/mljj8PevAJA6g7rAHfVe0UJJWz9GJCO0e2lQGiV6D+8WdgYFFI+NB/HML/vhT5UgSxZBa+CE4cvxSzXmSxQYRazRLCUjKs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
