travis:
  secure:
    BINSTAR_TOKEN: f3N/YiuYXa3Vm2lc6AFYDILCwP3hrjRygcS29GLSZsHcHtvDCnwodo60KqzVtpviJIJ2xjALdMjE7/5AC6NOddn7O/LmF/RmC2T+koAcbFRUOiwz4c3KM+CMhjmrrXAgwn1lL56nQdUElqegdk1mNS+7pjRhyP4FzY4qZx5iHZ61XqsGUi7f/X2U9y8sEfWOE7V8Ib3QUbt/ecC4nY9jimXEJBvPphv1z4q0zACAr9yK9YRC6AbhaCI6CfWYOHGHWOIga2sclMjMsaKR3lenmDtLLu/8wOTc0zV/xCug2ePHMB3DzPdRecYvIXkhm705Yu1C4tMk0M0LRXjBGUYJWfqMjSEX1naG+LUdMYWcKHlcVLnc2vIKW7LE1ztFcHuqE+y2A1bJYGM7pFDCmGdSNnMXfIHRE55I6R1LcfumEo7E6yHJYJcBC77LYV0b29fs6Wjczwm8oaEBTPGIQpMR4D8vqSXHfIrN3zo/hPyJ5AzopJ9xN+DEXlrHovEXX/iP9S3fKcGf0/bX5GlafiCukgODZp35WaSNM2gaqcDeqOLLFWvqQgZmNJelm+6OzLctlS1g6Bvo61OCMTShlasRz7GRLcALXPk23pn/CuE7REtGvhJiuPxKFeK3iqvwUn9vurduy0DtCMYpbwSur7HamyKXzIkhBQL2bxld/9dAZw0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
